/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeciesIndexRouteImport } from './routes/species.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as SpeciesSlugRouteImport } from './routes/species.$slug'
import { Route as ReportsDateRouteImport } from './routes/reports.$date'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpeciesRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const SpeciesSlugRoute = SpeciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpeciesRoute,
} as any)
const ReportsDateRoute = ReportsDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/forecast': typeof ForecastRoute
  '/rankings': typeof RankingsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/species': typeof SpeciesRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/trends': typeof TrendsRoute
  '/reports/$date': typeof ReportsDateRoute
  '/species/$slug': typeof SpeciesSlugRoute
  '/reports/': typeof ReportsIndexRoute
  '/species/': typeof SpeciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/forecast': typeof ForecastRoute
  '/rankings': typeof RankingsRoute
  '/subscribe': typeof SubscribeRoute
  '/trends': typeof TrendsRoute
  '/reports/$date': typeof ReportsDateRoute
  '/species/$slug': typeof SpeciesSlugRoute
  '/reports': typeof ReportsIndexRoute
  '/species': typeof SpeciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/forecast': typeof ForecastRoute
  '/rankings': typeof RankingsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/species': typeof SpeciesRouteWithChildren
  '/subscribe': typeof SubscribeRoute
  '/trends': typeof TrendsRoute
  '/reports/$date': typeof ReportsDateRoute
  '/species/$slug': typeof SpeciesSlugRoute
  '/reports/': typeof ReportsIndexRoute
  '/species/': typeof SpeciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conditions'
    | '/forecast'
    | '/rankings'
    | '/reports'
    | '/species'
    | '/subscribe'
    | '/trends'
    | '/reports/$date'
    | '/species/$slug'
    | '/reports/'
    | '/species/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions'
    | '/forecast'
    | '/rankings'
    | '/subscribe'
    | '/trends'
    | '/reports/$date'
    | '/species/$slug'
    | '/reports'
    | '/species'
  id:
    | '__root__'
    | '/'
    | '/conditions'
    | '/forecast'
    | '/rankings'
    | '/reports'
    | '/species'
    | '/subscribe'
    | '/trends'
    | '/reports/$date'
    | '/species/$slug'
    | '/reports/'
    | '/species/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsRoute: typeof ConditionsRoute
  ForecastRoute: typeof ForecastRoute
  RankingsRoute: typeof RankingsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SpeciesRoute: typeof SpeciesRouteWithChildren
  SubscribeRoute: typeof SubscribeRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/': {
      id: '/species/'
      path: '/'
      fullPath: '/species/'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof SpeciesRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/species/$slug': {
      id: '/species/$slug'
      path: '/$slug'
      fullPath: '/species/$slug'
      preLoaderRoute: typeof SpeciesSlugRouteImport
      parentRoute: typeof SpeciesRoute
    }
    '/reports/$date': {
      id: '/reports/$date'
      path: '/$date'
      fullPath: '/reports/$date'
      preLoaderRoute: typeof ReportsDateRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsDateRoute: typeof ReportsDateRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsDateRoute: ReportsDateRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SpeciesRouteChildren {
  SpeciesSlugRoute: typeof SpeciesSlugRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
}

const SpeciesRouteChildren: SpeciesRouteChildren = {
  SpeciesSlugRoute: SpeciesSlugRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
}

const SpeciesRouteWithChildren =
  SpeciesRoute._addFileChildren(SpeciesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsRoute: ConditionsRoute,
  ForecastRoute: ForecastRoute,
  RankingsRoute: RankingsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SpeciesRoute: SpeciesRouteWithChildren,
  SubscribeRoute: SubscribeRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
